MODEL: "ELMo"
GIT:
  addr: $REPO_ADDR 
  path: $ROOT_PATH/models_repo

ENV:
  http_proxy: $HTTP_PROXY
  https_proxy: $HTTPS_PROXY
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

TRAIN:
  -
    # 关联数据
    dataset:
      train:
        addr: $ROOT_PATH/dataset/ELMo/data
        path: $ROOT_PATH/models_repo/PaddleNLP/legacy/pretrain_language_models/ELMo/new_data  #在当前路径下创建data文件夹
    env:
      CUDA_VISIBLE_DEVICES: 1
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/models_repo/PaddleNLP/legacy/pretrain_language_models/ELMo
        cmd: python train.py --train_path=new_data/train/sentence_file_*  --test_path=new_data/dev/sentence_file_* --vocab_path new_data/vocabulary_min5k.txt --learning_rate 0.2 --use_gpu True --all_train_tokens 35479 --max_epoch 10 --log_interval 5 --dev_interval 20 --local True $@ --enable_ce --shuffle false --random_seed 100  1> card1.log
      -
        path: $ROOT_PATH/scripts/EMLo
        cmd: sh train.sh
    kpis:
      train_duration_card1:
        kpi_base: 9.3632504463
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
      train_loss_card1:
        kpi_base: 9.58
        threshold: 0.005
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/models_repo/PaddleNLP/legacy/pretrain_language_models/ELMo/card1.log

  -
    # 关联数据
    dataset:
      train:
        addr: $ROOT_PATH/dataset/ELMo/data
        path: $ROOT_PATH/models_repo/PaddleNLP/legacy/pretrain_language_models/ELMo/new_data  #在当前路径下创建data文件夹
    env:
      NCCL_SHM_DISABLE: 1
      CUDA_VISIBLE_DEVICES: 0, 1, 2, 3
    run: 
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/models_repo/PaddleNLP/legacy/pretrain_language_models/ELMo
        cmd: python train.py --train_path=new_data/train/sentence_file_*  --test_path=new_data/dev/sentence_file_* --vocab_path new_data/vocabulary_min5k.txt --learning_rate 0.2 --use_gpu True --all_train_tokens 35479 --max_epoch 10 --log_interval 5 --dev_interval 20 --local True $@ --enable_ce --shuffle false --random_seed 100  1> card4.log
    kpis:
      train_duration_card4:
        kpi_base: 70.77291488647
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
      train_loss_card4:
        kpi_base: 10.932211
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/models_repo/PaddleNLP/legacy/pretrain_language_models/ELMo/card4.log