MODEL: "XLNet"

EXEC:
  exec_cases: [DATA_PROC,TRAIN,EVAL,INFER]
  exec_priority: [p0, p1]

GIT:
  addr: $REPO_ADDR 
  path: $ROOT_PATH/models_repo

ENV:
  http_proxy: $HTTP_PROXY
  https_proxy: $HTTPS_PROXY

TRAIN:
  -
    priority: p0
    env:
      CUDA_VISIBLE_DEVICES: 2
    run: 
      -
        path: $ROOT_PATH/models_repo/PaddleNLP/legacy/pretrain_language_models/XLNet
        cmd: python run_classifier.py --data_dir data/STS-B --verbose True --shuffle false --init_checkpoint xlnet_cased_L-12_H-768_A-12/params --predict_dir exp/sts-b --model_config_path xlnet_cased_L-12_H-768_A-12/xlnet_config.json --uncased False --save_steps 50 --train_batch_size 1 --train_steps 50 --epoch 1 --skip_steps 10 --validation_steps 30 --task_name sts-b --warmup_steps 5 --random_seed 100 --spiece_model_file xlnet_cased_L-12_H-768_A-12/spiece.model --checkpoints checkpoints_sts-b --is_regression True --use_cuda True --eval_batch_size 4 --enable_ce 1> card1.log
    kpis:
      train_duration_sts_b_card1:
        latest: True
        kpi_base: 1.94770319
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
      train_cost_sts_b_card1:
        latest: True
        kpi_base: 2.735225
        threshold: 0.02
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/models_repo/PaddleNLP/legacy/pretrain_language_models/XLNet/card1.log
  - 
    priority: p0
    env:
      NCCL_SHM_DISABLE: 1
      CUDA_VISIBLE_DEVICES: 0, 1, 2, 3
    run: 
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/models_repo/PaddleNLP/legacy/pretrain_language_models/XLNet
        cmd: python run_classifier.py --data_dir data/STS-B --verbose True --shuffle false --init_checkpoint xlnet_cased_L-12_H-768_A-12/params --predict_dir exp/sts-b --model_config_path xlnet_cased_L-12_H-768_A-12/xlnet_config.json --uncased False --save_steps 50 --train_batch_size 1 --train_steps 50 --epoch 1 --skip_steps 10 --validation_steps 30 --task_name sts-b --warmup_steps 5 --random_seed 100 --spiece_model_file xlnet_cased_L-12_H-768_A-12/spiece.model --checkpoints checkpoints_sts-b --is_regression True --use_cuda True --eval_batch_size 4 --enable_ce 1> card4.log
    kpis:
      train_duration_sts_b_card4:
        latest: True
        kpi_base: 2.227002387047
        threshold: 0.04
        actived: True
        evaluation: "-"
        unit_repr: "s"
      train_cost_sts_b_card4:
        latest: True
        kpi_base: 1.640692
        threshold: 0.08
        evaluation: "-"
        actived: True
        unit_repr: "s"
    output: $ROOT_PATH/models_repo/PaddleNLP/legacy/pretrain_language_models/XLNet/card4.log



