MODEL: "deeplabv3"

PRIORITY: p0

VARIABLES:
  gpu_log_name: "deeplabv3_gpu.log"
  model_log_path: log/deeplabv3

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG

GIT:
  addr: $SEG_ADDR
  path: $ROOT_PATH/seg_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    tag: win_download_data
    run:
      -
        path: $ROOT_PATH/scripts/deeplabv3 #脚本的路径
        cmd: prepare.bat

TRAIN:
  -
    priority: p0
    tag: win_dy_gpu1
    env:
      CUDA_VISIBLE_DEVICES: 0
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/seg_repo/
        cmd: python train.py --config configs/deeplabv3/deeplabv3_resnet101_os8_cityscapes_1024x512_80k.yml --iters 3000 --batch_size 1 > $ROOT_PATH/$model_log_path/$gpu_log_name 2>&1
      -
        path: $PROJECT_ROOT/utils
        cmd: python process_log.py --log_path=$ROOT_PATH/$model_log_path/$gpu_log_name --reg="=" --obj=":"
    kpis:
      loss:
        latest: True
        actived: True
        kpi_base: 0.6111
        threshold: 0.05
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/$gpu_log_name
