MODEL: "MaskRCNN"

PRIORITY: p0

VARIABLES:
  cpu_log_name: "mask_rcnn_cpu.log"
  model_log_path: log/mask_rcnn

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG

GIT:
  addr: $DETECTION_ADDR
  path: $ROOT_PATH/detection_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    tag: win_download_data
    run:
      -
        path: $ROOT_PATH/scripts/mask_rcnn #脚本的路径
        cmd: prepare.bat

TRAIN:
  -
    priority: p0
    tag: win_st_gpu1
    env:
      CUDA_VISIBLE_DEVICES: 0
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/detection_repo/static/
        cmd: python tools/train.py -c configs/mask_rcnn_r50_1x.yml --enable_ce True -o use_gpu=true max_iters=100 TrainReader.shuffle=false > $ROOT_PATH/$model_log_path/$cpu_log_name 2>&1
      -
        path: $PROJECT_ROOT/utils
        cmd: python process_log.py --log_path=$ROOT_PATH/$model_log_path/$cpu_log_name --reg="'" --obj=""
    kpis:
      loss:
        latest: True
        actived: True
        kpi_base: 1.636072
        threshold: 0.05
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/$cpu_log_name
