MODEL: "ResNet50"

PRIORITY: p0_test

VARIABLES:
  gpu_log_name: "ResNet50_gpu.log"
  model_log_path: log/ResNet50

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG

GIT:
  addr: $ClAS_ADDR
  path: $ROOT_PATH/clas_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    tag: win_download_data
    run:
      -
        path: $ROOT_PATH/scripts/ResNet #脚本的路径
        cmd: prepare.bat

TRAIN:
  -
    priority: p0
    tag: win_dy_gpu1
    env:
      CUDA_VISIBLE_DEVICES: 0
      FLAGS_cudnn_deterministic: True
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/clas_repo/
        cmd:  python tools/train.py -c configs/ResNet/ResNet50.yaml -o pretrained_model="" -o epochs=30 -o TRAIN.batch_size=16 -o use_gpu=True -o validate=False > $ROOT_PATH/$model_log_path/$gpu_log_name 2>&1
    kpis:
      loss:
        latest: True
        actived: True
        kpi_base: 5.60227
        threshold: 0.01
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/$gpu_log_name
