MODEL: "ResNet50"

PRIORITY: p0

VARIABLES:
  gpu_log_name: "ResNet50_gpu.log"

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: [sing_card]

GIT:
  addr: $ClAS_ADDR
  path: $ROOT_PATH/clas_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    run:
      -
        path: $ROOT_PATH/scripts/ResNet #脚本的路径
        cmd: prepare.bat

TRAIN:
  -
    priority: p0
    tag: sing_card
    env:
      CUDA_VISIBLE_DEVICES: 0
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/clas_repo/
        cmd:  python tools/train.py -c configs/ResNet/ResNet50.yaml -o pretrained_model="" -o epochs=10 -o TRAIN.batch_size=16 -o use_gpu=True -o validate=False > $gpu_log_name 2>&1
    kpis:
      loss:
        latest: True
        kpi_base: 6.433232
        threshold: 0.01
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/clas_repo/$gpu_log_name
