MODEL: "deeplabv3"

PRIORITY: p0_delay  #波动太大，又不能迭代很久

VARIABLES:
  cpu_log_name: "deeplabv3_cpu.log"
  model_log_path: log/deeplabv3

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG

GIT:
  addr: $SEG_ADDR
  path: $ROOT_PATH/seg_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/scripts/deeplabv3 #脚本的路径
        cmd: bash prepare.sh

TRAIN:
  -
    priority: p0
    tag: linux_dy_cpu
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/seg_repo/
        cmd: python train.py --config configs/deeplabv3/deeplabv3_resnet101_os8_cityscapes_1024x512_80k.yml --iters 40 > $ROOT_PATH/$model_log_path/$cpu_log_name 2>&1
      -
        path: $PROJECT_ROOT/utils
        cmd: python process_log.py --log_path=$ROOT_PATH/$model_log_path/$cpu_log_name --reg="=" --obj=':'
    kpis:
      loss:
        latest: True
        actived: True
        kpi_base: 1.583920
        threshold: 0.2
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/$cpu_log_name
