MODEL: "MaskRCNN"

PRIORITY: p0

VARIABLES:
  cpu_log_name: "mask_rcnn_cpu.log"

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]

GIT:
  addr: $DETECTION_ADDR
  path: $ROOT_PATH/detection_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    run:
      -
        path: $ROOT_PATH/scripts/mask_rcnn #脚本的路径
        cmd: bash prepare.sh

TRAIN:
  -
    priority: p0

    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/detection_repo/
        cmd: python tools/train.py -c configs/mask_rcnn_r50_1x.yml -o max_iters=100 -o use_gpu=false > $cpu_log_name 2>&1
      -
        path: $PROJECT_ROOT/utils
        cmd: python process_log.py --log_path=$ROOT_PATH/detection_repo/$cpu_log_name --reg="'" --obj=""
    kpis:
      loss:
        latest: True
        kpi_base: 9.3632504463
        threshold: 0.01
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/detection_repo/$cpu_log_name
