MODEL: "ResNet50_vd"

PRIORITY: p0

VARIABLES:
  cpu_log_name: "ResNet50_vd_cpu.log"
  model_log_path: log/ResNet50_vd
EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG

GIT:
  addr: $ClAS_ADDR
  path: $ROOT_PATH/clas_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/dataset #脚本的路径
        cmd: ln -s $ROOT_PATH/dataset/ILSVRC2012 $ROOT_PATH/clas_repo/dataset/
      -
        path: $ROOT_PATH
        cmd: mkdir -p $ROOT_PATH/$model_log_path
      -
        path: $ROOT_PATH/Resnet
        cmd: cp -rf ResNet50_vd.yaml $ROOT_PATH/clas_repo/configs/ResNet/

TRAIN:
  -
    priority: p0
    tag: linux_dy_cpu
    env:
      FLAGS_cudnn_deterministic: True
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/clas_repo/
        cmd:  python tools/train.py -c configs/ResNet/ResNet50_vd.yaml -o use_mix=False -o pretrained_model="" -o epochs=3 -o TRAIN.batch_size=16 -o use_gpu=False -o validate=False > $ROOT_PATH/$model_log_path/$cpu_log_name 2>&1
    kpis:
      loss:
        latest: True
        actived: True
        kpi_base: 6.81480
        threshold: 0.05
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/$cpu_log_name
