MODEL: "ResNet50"

PRIORITY: p0

VARIABLES:
  cpu_log_name: "ResNet50_cpu.log"

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: [linux_cpu]

GIT:
  addr: $ClAS_ADDR
  path: $ROOT_PATH/clas_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    run:
      -
        path: $ROOT_PATH/dataset #脚本的路径
        cmd: ln -s $ROOT_PATH/dataset/ILSVRC2012 $ROOT_PATH/clas_repo/dataset/

TRAIN:
  -
    priority: p0
    tag: linux_cpu
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/clas_repo/
        cmd:  python tools/train.py -c configs/ResNet/ResNet50.yaml -o pretrained_model="" -o epochs=3 -o TRAIN.batch_size=16 -o use_gpu=False -o validate=False > $cpu_log_name 2>&1
    kpis:
      loss:
        latest: True
        kpi_base: 6.642184
        threshold: 0.02
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/clas_repo/$cpu_log_name
