MODEL: "ELMo"
GIT:
  addr: https://github.com/PaddlePaddle/models.git  
  path: task/models_repo

TRAIN:
  step1:
    path: task/models_repo/PaddleNLP/legacy/pretrain_language_models/ELMo
    # env:
    #   env1: None
    run: python train.py --train_path=data/train/sentence_file_*  --test_path=data/dev/sentence_file_* --vocab_path data/vocabulary_min5k.txt --learning_rate 0.2 --use_gpu False --all_train_tokens 35479 --max_epoch 1 --log_interval 5 --dev_interval 20 --local True --batch_size 32 --shuffle false --random_seed 100 --enable_ce| python _ce.py
    kpis:
      train_duration_card1:
        base: 1684.7283911705017
        threshold: 0.005
        actived: True
      train_loss_card1:
        base: 17.065272
        threshold: 0.01
        actived: True
    output: task/models_repo/PaddleNLP/legacy/pretrain_language_models/ELMo



