MODEL: "bert" # 模型名
PRIORITY: p0
GIT:
  addr: $NLP_ADDR
  path: $ROOT_PATH/nlp_repo


VARIABLES:
  model_scripts_path: scripts/bert/ #脚本的路径
  model_log_path: log/bert

EXEC:
  exec_cases: [DATA_PROC, TRAIN, INFER]
  exec_priority: [p0,p1]
  exec_tag: $EXEC_TAG

#测试套
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh

TRAIN: # 训练步骤
  #pretrain
  -
    priority: p0
    tag: linux_dy_gpu1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh 'single' $SET_CUDA

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 11.921639
        threshold: 0.001
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/single_card_train.log

  -
    priority: p1
    tag: linux_dy_gpu4
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh 'multi' $SET_MULTI_CUDA

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 11.921639
        threshold: 0.001
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/multi_cards_train.log

  # finetune
  - #可以有多步
    priority: p0
    tag: linux_finetune_gpu1_SST-2
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh finetune.sh 'SST-2' $SET_CUDA

    kpis: #kpi指标
      acc:
        latest: True
        kpi_base: 0.5860
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/SST-2-_fine-tune.log

  - #可以有多步
    priority: p0
    tag: linux_finetune_gpu1_QNLI
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh finetune.sh 'QNLI' $SET_CUDA

    kpis: #kpi指标
      acc:
        latest: True
        kpi_base: 0.6797
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/QNLI-_fine-tune.log

  - #可以有多步
    priority: p9
    tag: linux_finetune_gpu1_CoLA
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh finetune.sh 'CoLA' $SET_CUDA

    kpis: #kpi指标
      acc:
        latest: True
        kpi_base: 0.0001
        threshold: 1
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/CoLA-_fine-tune.log

  - #可以有多步
    priority: p0
    tag: linux_finetune_gpu1_MRPC
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh finetune.sh 'MRPC' $SET_CUDA

    kpis: #kpi指标
      f1:
        latest: True
        kpi_base: 0.81287
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
      acc:
        latest: True
        kpi_base: 0.6863
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/MRPC-_fine-tune.log

  - #可以有多步
    priority: p0
    tag: linux_finetune_gpu1_STS-B
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh finetune.sh 'STS-B' $SET_CUDA

    kpis: #kpi指标
      pearson:
        latest: True
        kpi_base: 0.27724463321910015
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
      spearman:
        latest: True
        kpi_base: 0.19406690225195655
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/STS-B-_fine-tune.log

  - #可以有多步
    priority: p0
    tag: linux_finetune_gpu1_QQP
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh finetune.sh 'QQP' $SET_CUDA

    kpis: #kpi指标
      acc:
        latest: True
        kpi_base: 0.631288647044274
        threshold: 0.001
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/QQP-_fine-tune.log

  - #可以有多步
    priority: p0
    tag: linux_finetune_gpu1_MNLI
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh finetune.sh 'MNLI' $SET_CUDA

    kpis: #kpi指标
      acc:
        latest: True
        kpi_base: 0.3846
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/MNLI-_fine-tune.log

  - #可以有多步
    priority: p0
    tag: linux_finetune_gpu1_RTE
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh finetune.sh 'RTE' $SET_CUDA

    kpis: #kpi指标
      acc:
        latest: True
        kpi_base: 0.5776
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/RTE-_fine-tune.log

INFER:
  - 
    priority: p0
    tag: linux_dy_gpu1
    env: #去掉，自动调度
        CUDA_VISIBLE_DEVICES: $SET_CUDA
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh
    kpis:
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/bert_predict.log

