MODEL: "bisenet_cityscapes_1024x1024_160k" # 模型名
PRIORITY: P0
GIT:
  addr: $SEG_ADDR
  path: $ROOT_PATH/seg_repo

VARIABLES:
  model_scripts_path: scripts/bisenet_cityscapes_1024x1024_160k/ #脚本的路径
  model_log_path: log/bisenet_cityscapes_1024x1024_160k

EXEC:
  exec_cases: [DATA_PROC,TRAIN,EVAL]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG

#测试套
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh

TRAIN: # 训练步骤
  -
    priority: p0
    tag: linux_dy_gpu2
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh 'multi'

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 3.7913
        threshold: 0.3
        actived: True
        evaluation: "-"
        unit_repr: None
      ips:
        latest: True
        kpi_base: 3.1433
        threshold: 0.5
        actived: True
        evaluation: "+"
        unit_repr: "images/s"
    output: $ROOT_PATH/$model_log_path/bisenet_cityscapes_1024x1024_160k_train_multi.log

  -
    priority: p0
    tag: linux_dy_gpu1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh 'single'

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 5.7282
        threshold: 0.7
        actived: True
        evaluation: "-"
        unit_repr: None
      ips:
        latest: True
        kpi_base: 3.2050
        threshold: 0.7
        actived: True
        evaluation: "+"
        unit_repr: "images/s"
    output: $ROOT_PATH/$model_log_path/bisenet_cityscapes_1024x1024_160k_train_single.log


EVAL:
  - #可以有多步
    priority: p0
    tag: linux_dy_gpu1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh eval.sh 'single'

    kpis: #kpi指标
      exit_code:
        latest: True
        kpi_base: 1.354209
        threshold: 0.08
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/bisenet_cityscapes_1024x1024_160k_eval_single.log

  - #可以有多步
    priority: p0
    tag: linux_dy_gpu2
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh eval.sh 'multi'

    kpis: #kpi指标
      exit_code:
        latest: True
        kpi_base: 1.354209
        threshold: 0.08
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/bisenet_cityscapes_1024x1024_160k_eval_multi.log
#INFER:
#  -
#    priority: p1
#    env: #去掉，自动调度
#        CUDA_VISIBLE_DEVICES: $SET_CUDA
#    run:
#      -
#        path: $ROOT_PATH/$model_scripts_path
#        cmd: sh infer.sh >$model_log_path/infer.log
#    output: $ROOT_PATH/$model_log_path/infer.log
#
#EXPORT:
#  -
#    priority: p1
#    env: #去掉，自动调度
#        CUDA_VISIBLE_DEVICES: $SET_CUDA
#    run:
#      -
#        path: $ROOT_PATH/$model_scripts_path
#        cmd: sh export.sh >$model_log_path/export.log
#    output: $ROOT_PATH/$model_log_path/export.log
#
#PYTHON_INFER:
#  -
#    priority: p1
#    env: #去掉，自动调度
#        CUDA_VISIBLE_DEVICES: $SET_CUDA
#    run:
#      -
#        path: $ROOT_PATH/$model_scripts_path
#        cmd: sh python_infer.sh >$model_log_path/python_infer.log
#    output: $ROOT_PATH/$model_log_path/python_infer.log

