MODEL: "DeepLabv3p"

PRIORITY: P0

VARIABLES:
  single_log_name: "deeplabv3p_single_card.log"
  multi_log_name: "deeplabv3p_multi_card.log"
  model_log_path: log/deeplabv3p

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG

GIT:
  addr: $SEG_ADDR
  path: $ROOT_PATH/seg_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/scripts/deeplabv3p #脚本的路径
        cmd: bash prepare.sh

TRAIN:
  -
    priority: p0
    tag: linux_dy_gpu1
    env:
      CUDA_VISIBLE_DEVICES: 1
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/seg_repo/
        cmd: python train.py --config configs/deeplabv3p/deeplabv3p_resnet50_os8_cityscapes_1024x512_80k.yml --iters 2000 > $ROOT_PATH/$model_log_path/$single_log_name 2>&1
      -
        path: $PROJECT_ROOT/utils
        cmd: python process_log.py --log_path=$ROOT_PATH/$model_log_path/$single_log_name --reg="=" --obj=':'
    kpis:
      loss:
        latest: True
        kpi_base: 0.7510
        threshold: 0.1
        actived: True
        evaluation: "-"
        unit_repr: None
      ips:
        latest: True
        kpi_base: 3.0780
        threshold: 0.03
        actived: True
        evaluation: "+"
        unit_repr: "images/s"
    output: $ROOT_PATH/$model_log_path/$single_log_name

  -
    priority: p0
    tag: linux_dy_gpu4
    env:
      NCCL_SHM_DISABLE: 1
      CUDA_VISIBLE_DEVICES: 1, 2, 3, 4
    run: 
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/seg_repo/
        cmd: python train.py  --config configs/deeplabv3p/deeplabv3p_resnet50_os8_cityscapes_1024x512_80k.yml --iters 2000 > $ROOT_PATH/$model_log_path/$multi_log_name 2>&1
      -
        path: $PROJECT_ROOT/utils
        cmd: python process_log.py --log_path=$ROOT_PATH/$model_log_path/$multi_log_name --reg="=" --obj=":"
    kpis:
      loss:
        latest: True
        kpi_base: 0.2701
        threshold: 0.09
        actived: True
        evaluation: "-"
        unit_repr: None
      ips:
        latest: True
        kpi_base: 2.9921
        threshold: 0.03
        actived: True
        evaluation: "+"
        unit_repr: "images/s"
    output: $ROOT_PATH/$model_log_path/$multi_log_name