MODEL: "DeepLabv3"

PRIORITY: p0

ENV:
  http_proxy: http://172.19.57.45:3128
  https_proxy: http://172.19.57.45:3128

VARIABLES:
  single_log_name: "deeplabv3_single_card.log"
  multi_log_name: "deeplabv3_multi_card.log"

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: [sing_card, multi_card4]

GIT:
  addr: $SEG_ADDR
  path: $ROOT_PATH/seg_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    run:
      -
        path: $ROOT_PATH/scripts/deeplabv3 #脚本的路径
        cmd: sh prepare.sh

TRAIN:
  -
    priority: p0
    tag: sing_card
    env:
      CUDA_VISIBLE_DEVICES: 1
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/seg_repo/
        cmd: python train.py --config configs/deeplabv3/deeplabv3_resnet101_os8_cityscapes_1024x512_80k.yml --iters 100 > $single_log_name 2>&1
      -
        path: $PROJECT_ROOT/utils
        cmd: python process_log.py --log_path=$ROOT_PATH/seg_repo/$single_log_name --reg="=" --obj=':'
    kpis:
      loss:
        latest: True
        kpi_base: 1.646840
        threshold: 0.2
        evaluation: "-"
    output: $ROOT_PATH/seg_repo/$single_log_name

  -
    priority: p0
    tag: multi_card4
    env:
      NCCL_SHM_DISABLE: 1
      CUDA_VISIBLE_DEVICES: 0, 1, 2, 3
    run: 
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/seg_repo/
        cmd: python train.py  --config configs/deeplabv3/deeplabv3_resnet101_os8_cityscapes_1024x512_80k.yml --iters 100 > $multi_log_name 2>&1
      -
        path: $PROJECT_ROOT/utils
        cmd: python process_log.py --log_path=$ROOT_PATH/seg_repo/$multi_log_name --reg="=" --obj=":"
    kpis:
      loss:
        latest: True
        actived: True
        kpi_base: 1.65584
        threshold: 0.2
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/seg_repo/$multi_log_name