MODEL: "DeepLabv3"

PRIORITY: p0

VARIABLES:
  single_log_name: "deeplabv3_single_card.log"
  multi_log_name: "deeplabv3_multi_card.log"

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]

GIT:
  addr: $SEG_ADDR
  path: $ROOT_PATH/seg_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    run:
      -
        path: $ROOT_PATH/scripts/deeplabv3 #脚本的路径
        cmd: sh prepare.sh

TRAIN:
  -
    priority: p0
    env:
      CUDA_VISIBLE_DEVICES: 1
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/seg_repo/
        cmd: python train.py --config configs/deeplabv3/deeplabv3_resnet101_os8_cityscapes_1024x512_80k.yml --iters 100 > $single_log_name 2>&1
    kpis:
      loss:
        latest: True
        kpi_base: 9.3632504463
        threshold: 0.01
        evaluation: "-"
    output: $ROOT_PATH/seg_repo/$single_log_name

  -
    priority: p0
    env:
      NCCL_SHM_DISABLE: 1
      CUDA_VISIBLE_DEVICES: 0, 1, 2, 3
    run: 
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/seg_repo/
        cmd: python train.py  --config configs/deeplabv3/deeplabv3_resnet101_os8_cityscapes_1024x512_80k.yml --iters 100 > $multi_log_name 2>&1
    kpis:
      loss:
        latest: True
        actived: True
        kpi_base: 70.77291488647
        threshold: 0.01
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/seg_repo/$multi_log_name