MODEL: "GPT-2" # 模型名
PRIORITY: P0
GIT:
  addr: $NLP_ADDR
  path: $ROOT_PATH/nlp_repo

ENV:
  http_proxy: $HTTP_PROXY
  https_proxy: $HTTPS_PROXY
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/GPT-2/ #脚本的路径
  model_log_path: log/GPT-2

EXEC:
  exec_cases: [DATA_PROC,TRAIN, INFER, EVAL]
  exec_priority: [p0, p1]
  exec_tag: $EXEC_TAG

#测试套
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash data_proc.sh

TRAIN: # 训练步骤
  -
    priority: p0
    tag: linux_dy_gpu1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: 1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash train.sh 'single' 'gpu' 
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 10.984482
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/single_card_train.log
  -
    priority: p1
    tag: linux_dy_gpu4

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash train.sh 'multi' 'gpu' $SET_MULTI_CUDA
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 10.972841
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output:  $ROOT_PATH/$model_log_path/multi_cards_train.log

INFER:
  - 
    priority: p1
    tag: linux_dy_gpu1
    env: #去掉，自动调度
        CUDA_VISIBLE_DEVICES: $SET_CUDA
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash infer.sh
    kpis:
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/infer.log

EVAL:
  - 
    priority: p1
    tag: linux_dy_gpu1
    env: #去掉，自动调度
        CUDA_VISIBLE_DEVICES: $SET_CUDA
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash eval.sh $XPU
    kpis:
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/eval_$XPU.log