MODEL: "lexical_analysis" # 模型名
PRIORITY: p0
GIT:
  addr: $NLP_ADDR
  path: $ROOT_PATH/nlp_repo

ENV:
  http_proxy: $HTTP_PROXY
  https_proxy: $HTTPS_PROXY
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/lexical_analysis/ #脚本的路径
  model_log_path: log/lexical_analysis/

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0,p1]
  exec_tag: [single_card]
#测试套
DATA_PROC:
  -
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash data_proc.sh
TRAIN: # 训练步骤
  -
    priority: p0
    tag: single_card
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: 1  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash train.sh gpu "single" 
    kpis: #kpi指标
      precision:
        latest: True
        kpi_base: 0.5098
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
      recall:
        latest: True
        kpi_base: 0.582
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
      f1:
        latest: True
        kpi_base: 0.5438
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/single_card_train.log
