MODEL: "MaskRCNN"

PRIORITY: p0

ENV:
  http_proxy: http://172.19.57.45:3128
  https_proxy: http://172.19.57.45:3128

VARIABLES:
  single_log_name: "mask_rcnn_single_card.log"
  multi_log_name: "mask_rcnn_multi_card.log"
  model_log_path: log/mask_rcnn

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG

GIT:
  addr: $DETECTION_ADDR
  path: $ROOT_PATH/detection_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/scripts/mask_rcnn #脚本的路径
        cmd: sh prepare.sh

TRAIN:
  -
    priority: p0
    tag: linux_st_gpu1
    env:
      CUDA_VISIBLE_DEVICES: 1
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/detection_repo/static/
        cmd: python tools/train.py -c configs/mask_rcnn_r50_fpn_1x.yml --enable_ce True -o use_gpu=true max_iters=1000 TrainReader.shuffle=false > $ROOT_PATH/$model_log_path/$single_log_name 2>&1
      -
        path: $PROJECT_ROOT/utils
        cmd: python process_log.py --log_path=$ROOT_PATH/$model_log_path/$single_log_name --reg="'" --obj=""
    kpis:
      loss:
        latest: True
        actived: True
        kpi_base: 1.23475
        threshold: 0.08
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/$single_log_name

  -
    priority: p0
    tag: linux_st_gpu8
    env:
      NCCL_SHM_DISABLE: 1
      CUDA_VISIBLE_DEVICES: 0, 1, 2, 3, 4, 5, 6, 7
    run: 
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/detection_repo/static/
        cmd: python tools/train.py -c configs/mask_rcnn_r50_fpn_1x.yml --enable_ce True -o use_gpu=true max_iters=1000 TrainReader.shuffle=false > $ROOT_PATH/$model_log_path/$multi_log_name 2>&1
      -
        path: $PROJECT_ROOT/utils
        cmd: python process_log.py --log_path=$ROOT_PATH/$model_log_path/$multi_log_name --reg="'" --obj=""

    kpis:
      loss:
        latest: True
        actived: True
        kpi_base: 2.5345
        threshold: 0.08
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/$multi_log_name