MODEL: "MaskRCNN"

PRIORITY: p0

ENV:
  http_proxy: http://172.19.57.45:3128
  https_proxy: http://172.19.57.45:3128

VARIABLES:
  single_log_name: "mask_rcnn_single_card.log"
  multi_log_name: "mask_rcnn_multi_card.log"

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: [sing_card, multi_card4]

GIT:
  addr: $DETECTION_ADDR
  path: $ROOT_PATH/detection_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    run:
      -
        path: $ROOT_PATH/scripts/mask_rcnn #脚本的路径
        cmd: sh prepare.sh

TRAIN:
  -
    priority: p0
    tag: sing_card
    env:
      CUDA_VISIBLE_DEVICES: 1
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/detection_repo/
        cmd: python tools/train.py -c configs/mask_rcnn_r50_1x.yml --enable_ce True -o use_gpu=true max_iters=100 TrainReader.shuffle=false > $single_log_name 2>&1
      -
        path: $PROJECT_ROOT/utils
        cmd: python process_log.py --log_path=$ROOT_PATH/detection_repo/$single_log_name --reg="'" --obj=""
    kpis:
      loss:
        latest: True
        kpi_base: 1.679741
        threshold: 0.07
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/detection_repo/$single_log_name

  -
    priority: p0
    tag: multi_card4
    env:
      NCCL_SHM_DISABLE: 1
      CUDA_VISIBLE_DEVICES: 1, 2, 3, 4
    run: 
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/detection_repo/
        cmd: python tools/train.py -c configs/mask_rcnn_r50_1x.yml --enable_ce True -o use_gpu=true max_iters=100 TrainReader.shuffle=false > $multi_log_name 2>&1
      -
        path: $PROJECT_ROOT/utils
        cmd: python process_log.py --log_path=$ROOT_PATH/detection_repo/$multi_log_name --reg="'" --obj=""

    kpis:
      loss:
        latest: True
        actived: True
        kpi_base: 1.649808
        threshold: 0.06
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/detection_repo/$multi_log_name