MODEL: "MobileNetV3_large_x1_0" # 模型名
PRIORITY: p0
GIT:
  addr: $ClAS_ADDR
  path: $ROOT_PATH/clas_repo

VARIABLES:
  model_scripts_path: scripts/MobileNetV3_large_x1_0/ #脚本的路径
  model_log_path: log/MobileNetV3_large_x1_0

EXEC:
  exec_cases: [DATA_PROC, TRAIN]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG


#测试套 
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/dataset #脚本的路径
        cmd: ln -s $ROOT_PATH/dataset/ILSVRC2012 $ROOT_PATH/clas_repo/dataset/
      -
        path: $ROOT_PATH
        cmd: mkdir -p $ROOT_PATH/$model_log_path

#测试套
TRAIN: # 训练步骤
  -
    priority: p0
    tag: linux_dy_gpu1
    env:
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置
      FLAGS_cudnn_deterministic: True

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash train.sh $XPU single

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.75525
        threshold: 0.05
        actived: True
        evaluation: "-"
    output: $ROOT_PATH/$model_log_path/train_single_$XPU.log
  -
    priority: p0
    tag: linux_dy_gpu4
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
      FLAGS_cudnn_deterministic: True

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash train.sh $XPU multi

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.69933
        threshold: 0.05
        actived: True
        evaluation: "-"
    output: $ROOT_PATH/$model_log_path/train_multi_$XPU.log
