MODEL: "ResNet50_vd"

PRIORITY: p0

ENV:
  http_proxy: http://172.19.57.45:3128
  https_proxy: http://172.19.57.45:3128


VARIABLES:
  single_log_name: "ResNet50_vd_single_card.log"
  multi_log_name: "ResNet50_vd_multi_card.log"

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: [sing_card, multi_card4]

GIT:
  addr: $ClAS_ADDR
  path: $ROOT_PATH/clas_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    run:
      -
        path: $ROOT_PATH/dataset #脚本的路径
        cmd: ln -s $ROOT_PATH/dataset/ILSVRC2012 $ROOT_PATH/clas_repo/dataset/

TRAIN:
  -
    priority: p0
    tag: sing_card
    env:
      CUDA_VISIBLE_DEVICES: 1
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/clas_repo/
        cmd:  python tools/train.py -c configs/ResNet/ResNet50_vd.yaml -o pretrained_model="" -o epochs=20 -o TRAIN.batch_size=128 -o use_gpu=True -o validate=False > $single_log_name 2>&1
    kpis:
      loss:
        latest: True
        kpi_base: 6.149695
        threshold: 0.05
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/clas_repo/$single_log_name

  -
    priority: p0
    tag: multi_card4
    env:
      NCCL_SHM_DISABLE: 1
      CUDA_VISIBLE_DEVICES: 0, 1, 2, 3
    run: 
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/clas_repo/
        cmd: python tools/train.py -c configs/ResNet/ResNet50_vd.yaml -o pretrained_model="" -o epochs=20 -o TRAIN.batch_size=128 -o use_gpu=True -o validate=False > $multi_log_name 2>&1
    kpis:
      loss:
        latest: True
        kpi_base: 6.172326
        threshold: 0.05
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/clas_repo/$multi_log_name