MODEL: "ResNet50_vd"

PRIORITY: p0

ENV:
  http_proxy: http://172.19.57.45:3128
  https_proxy: http://172.19.57.45:3128


VARIABLES:
  single_log_name: "ResNet50_vd_single_card.log"
  multi_log_name: "ResNet50_vd_multi_card.log"
  model_log_path: log/ResNet50_vd

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG

GIT:
  addr: $ClAS_ADDR
  path: $ROOT_PATH/clas_repo

#测试套 
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/dataset #脚本的路径
        cmd: ln -s $ROOT_PATH/dataset/ILSVRC2012 $ROOT_PATH/clas_repo/dataset/
      -
        path: $ROOT_PATH
        cmd: mkdir -p $ROOT_PATH/$model_log_path
      # 覆盖原有的配置
      -
        path: $ROOT_PATH/Resnet
        cmd: cp -rf ResNet50_vd.yaml $ROOT_PATH/clas_repo/configs/ResNet/


TRAIN:
  -
    priority: p0
    tag: linux_dy_gpu1
    env:
      CUDA_VISIBLE_DEVICES: 1
    run:
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/clas_repo/
        cmd:  python tools/train.py -c configs/ResNet/ResNet50_vd.yaml -o pretrained_model="" -o epochs=30 -o TRAIN.batch_size=128 -o use_gpu=True -o validate=False > $ROOT_PATH/$model_log_path/$single_log_name 2>&1
    kpis:
      loss:
        latest: True
        actived: True
        kpi_base: 6.149695
        threshold: 0.05
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/$single_log_name

  -
    priority: p0
    tag: linux_dy_gpu4
    env:
      NCCL_SHM_DISABLE: 1
      CUDA_VISIBLE_DEVICES: 1, 2, 3, 4
    run: 
      -
        # 进入一下路径在一下路径下执行命令
        path: $ROOT_PATH/clas_repo/
        cmd: python tools/train.py -c configs/ResNet/ResNet50_vd.yaml -o pretrained_model="" -o epochs=30 -o TRAIN.batch_size=128 -o use_gpu=True -o validate=False > $ROOT_PATH/$model_log_path/$multi_log_name 2>&1
    kpis:
      loss:
        latest: True
        actived: True
        kpi_base: 6.172326
        threshold: 0.05
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/$multi_log_name